host: 0.0.0.0
port: 8317
tls:
  enable: false
remote-management:
  allow-remote: true
  secret-key: $2a$10$egMFoi6FLCf70f9tGmvPOOnE2lKtqlZvCKO.1d/CyncWXz8v9vc/C
  disable-control-panel: false
  panel-github-repository: https://github.com/router-for-me/Cli-Proxy-API-Management-Center
auth-dir: ~/.cli-proxy-api
api-keys:
  - fyz040913
debug: true
pprof:
  enable: false
  addr: 127.0.0.1:8316
commercial-mode: false
logging-to-file: true
logs-max-total-size-mb: 1000
error-logs-max-files: 10
usage-statistics-enabled: true
proxy-url: http://127.0.0.1:7890
force-model-prefix: false
passthrough-headers: false
request-retry: 1
max-retry-interval: 8
quota-exceeded:
  switch-project: true
  switch-preview-model: true
routing:
  strategy: round-robin
ws-auth: false
nonstream-keepalive-interval: 0
